config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'

  resources :notes do
    resources :items do
      member do
        patch 'completed'
      end
    end
  end

end

app/models/item.rb
class Item
  include Mongoid::Document
  field :content, type: String
  field :completed_at, type: DateTime

  validates_presence_of :content
  validates_length_of :content, minimum: 3
  embedded_in :note

  scope :complete, -> { where(:completed_at.exists => true ) }
  #scope :incomplete, -> { where(completed_at: nil) }
  scope :incomplete, -> { where(:completed_at.exists => false ) }
  
  def completed?
    !completed_at.blank?
  end
end

app/models/note.rb
class Note
  include Mongoid::Document
  field :title, type: String
  field :content, type: String

  #validate
  validates_presence_of :title
  validates_length_of :title, minimum: 3
  validates_presence_of :content

  embeds_many :items

  def has_completed_items?
    items.complete.size > 0
  end

  def has_incomplete_items?
    items.incomplete.size > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_note

  def index
  end

  def new
    @item = @note.items.new
  end

  def create
    @item = @note.items.new(item_params)
    if @item.save
      flash[:success] = "Added note item."
      redirect_to note_items_path
    else
      flash[:error] = "adding item failed."
      render action: :new
    end
  end

  def edit
    @item = @note.items.find(params[:id])
  end

  def update
    @item = @note.items.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = "item has been updated."
      redirect_to note_items_path
    else
      flash[:error] = "update item failed."
      render action: :edit
    end
  end

  def destroy
    @item = @note.items.find(params[:id])
    @item.destroy
    flash[:notice] = "Item has been deleted."
    redirect_to note_items_path
  end

  def completed
    @item = @note.items.find(params[:id])
    @item.update_attributes(completed_at: Time.now)
    redirect_to note_items_path, notice: "Item has been marked as completed"
  end

  private

    def set_note
      @note = Note.find(params[:note_id])
    end

    def item_params
      params.require(:item).permit(:content)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/items/_form.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@item.errors.count,"error")%>prohibited this item from being saved:
    </h2>
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= f.label :content %>
<%= f.text_field :content %>

app/views/items/edit.html.erb
<%= form_for [@note,@item] do |f| %>
<%= render 'form', f: f %>
<%= f.submit "Update" %>
<% end %>

app/views/items/index.html.erb
<h2><%= @note.title %></h2>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Content</th>
      <th>Operate</th>
    </tr>
  </thead>
  <tbody class="note_items">
  <% @note.items.each do |item| %>
    <tr id="note_item_<%= item.id %>">
      <% if item.completed? %>
        <td><%= item.completed_at %></td>
      <% else %>
        <td><%= link_to "Complete", completed_note_item_path(@note,item), method: :patch %></td>
      <% end %>
      <td><%= item.content %></td>
      <td><%= link_to "Edit", edit_note_item_path(@note,item) %>
      <%= link_to "Delete", note_item_path(@note,item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p>
  <%= link_to "New item", new_note_item_path(@note) %>
</p>

app/views/items/new.html.erb
<%= form_for [@note,@item] do |f| %>
<%= render 'form',f: f %>
<%= f.submit "Save" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webnotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <h1><%= link_to "WebNotes", root_path %></h1>
  <ul>
    <li><%= link_to "List Notes", notes_path %></li>
  </ul>
</nav>
<br class="clear"/>

<% flash.each do |type,msg| %>
<div class="alert flash <%= type %>">
  <%= msg %>
</div>
<% end -%>
<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr id=<%= "note_"+note.id %>>
        <td><%= note.title %></td>
        <td><%= note.content %></td>
        <td>
          <%= link_to "Items", note_items_path(note) %>
          <%= link_to 'Show', note %>
          <%= link_to 'Edit', edit_note_path(note) %>
          <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<h1><%= @note.title %></h1>
<h2><%= @note.content %></h2>

<% if @note.has_incomplete_items? %>
  <h3>Incomplete items:</h3>
  <ul>
    <% @note.items.incomplete.each do |item| %>
      <li><%= item.content %></li>
    <% end %>
  </ul>
<% end %>

<% if @note.has_completed_items? %>
  <h3>Completed items:</h3>
  <ul>
    <% @note.items.complete.each do |item| %>
      <li><%= item.content %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>